.catalog:
  name: traefik
  version: v1.2.1-rancher1
  description: |
    Traefik load balancer.
  minimum_rancher_version: v1.5.0
  maintainer: "Samuel Taylor <samtaylor.uk@gmail.com>"
  uuid: traefik-0
  questions:
    - variable: "host_label"
      description: "Host label where to run traefik service."
      label: "Host label:"
      required: true
      default: "traefik_lb=true"
      type: "string"

    - variable: "http_port"
      description: "Traefik http public port to listen."
      label: "Http port:"
      required: true
      default: 80
      type: "int"

    - variable: "https_port"
      description: "Traefik https public port to listen."
      label: "Https port:"
      required: true
      default: 443
      type: "int"

    - variable: "admin_port"
      description: "Traefik admin public port to listen."
      label: "Admin port:"
      required: true
      default: 8000
      type: "int"

    - variable: "https_enable"
      label: "Enable HTTPS:"
      description: |
        Enable https working mode. If you activate, you need to fill SSL key and SSL crt in order to work.
      default: false
      required: true
      type: enum
      options:
        - false
        - true
        - only

    - variable: "acme_enable"
      description: "Enable acme support on traefik."
      label: "Enable ACME:"
      required: true
      default: false
      type: "boolean"

    - variable: "acme_email"
      description: "ACME user email."
      label: "ACME email:"
      required: true
      default: "test@traefik.io"
      type: "string"

traefik:
  retain_ip: true
  health_check:
    port: 8000
    interval: 5000
    unhealthy_threshold: 3
    request_line: 'GET /dashboard/# HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 5000
